# Copyright (c) Luppes Consulting, Inc.
# Licensed under the MIT License.
# To install mkdocs on Windows:
#   python -m pip install mkdocs
# To run locally: 
#   python -m mkdocs serve
#   See: https://www.mkdocs.org/getting-started/
# To create a static docs site that will automatically be deployed:
#   python -m mkdocs gh-deploy
#   See: https://www.mkdocs.org/user-guide/deploying-your-docs/
#   This repo is set to deploy to https://lluppesms.github.io/Docs
# I've set up a CNAME alias of http://docs.luppes.com
#   FYI - To make that work with the gh-deploy command, you have to include
#   a CNAME file in the docs folder, otherwise it removes the CNAME.

site_name: Lyle's Reference Library
site_url: https://lluppesms.github.io/Docs
site_description: Helpful docs from Lyle
site_author: Lyle Luppes

extra_css:
- assets/stylesheets/extra.css

theme:
  language: en
  name: readthedocs  # material  (missing)
  font:
    text: Roboto
  palette:
    primary: black
    accent: blue
  logo: assets/images/LyleHeader.png
  favicon: assets/images/LyleIcon-64.png
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.indexes
  - navigation.sections:
      level: 1
  - navigation.tabs
  - content.code.annotate
  - content.tabs.link

nav:
  - Home: index.md

  - Azure DevOps Setup:
    - Create Azure DevOps Service Connections: CreateServiceConnections.md
    - Create Azure DevOps Environments: CreateDevOpsEnvironments.md
    - Create Azure DevOps Variable Groups: CreateDevOpsVariableGroups.md
    - Create Azure DevOps Pipelines: CreateNewPipeline.md

  - Azure Developer Command (azd):
    - Deploying with 'azd' (Azure Developer Command): AzdDeploy.md
    - Making Your Project 'azd' Compatible: AzdCompatibility.md

  - Application Insights:
    - Querying Logs in Application Insights: ReadAppInsightsLogFiles.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: '#'
      separator: '-'
